#!/bin/sh

fancy_echo() {
  local fmt="$1"
  shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  zshrc="$HOME/.zshrc"

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >>"$zshrc"
    else
      printf "\n%s\n" "$text" >>"$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

# Determine Homebrew prefix
arch="$(uname -m)"
if [ "$arch" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

case "$SHELL" in
*/zsh) : ;;
*)
  fancy_echo "Changing your shell to zsh ..."
  chsh -s "$(which zsh)"
  ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed >/dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  append_to_zshrc '# recommended by brew doctor'

  # shellcheck disable=SC2016
  append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

  export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Setting up dotfiles ..."

if [ ! -d "$HOME/.dotfiles/" ]; then
  git clone git@github.com:ianagne/dotfiles.git $HOME/.dotfiles
fi

fancy_echo "Updating Homebrew formulae ..."
brew update
brew bundle --file="~/.dotfiles/Brewfile"

rcup

fancy_echo "Symlinking neovim configuration ..."

mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
if [ ! -L "$XDG_CONFIG_HOME/nvim" ]; then
  ln -s $HOME/.lua $XDG_CONFIG_HOME/nvim
fi

if [ ! -e "$XDG_CONFIG_HOME/nvim/init.lua" ]; then
  ln -s $HOME/.init.lua $XDG_CONFIG_HOME/nvim/init.lua
fi

fancy_echo "Configuring asdf version manager..."
if [ ! -d "$HOME/.asdf" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.3.0
fi

install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  fi
}

# shellcheck disable=SC1090
source "$HOME/.asdf/asdf.sh"
install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
install_asdf_plugin "python" "https://github.com/tuvistavie/asdf-python.git"
install_asdf_plugin "erlang" "https://github.com/asdf-vm/asdf-erlang.git"
install_asdf_plugin "elixir" "https://github.com/asdf-vm/asdf-elixir.git"
install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"

install_asdf_language() {
  local language="$1"
  local version
  version="$(asdf list-all "$language" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

fancy_echo "Installing latest Ruby..."
install_asdf_language "ruby"
gem update --system
gem_install_or_update "bundler"
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

fancy_echo "Installing latest Erlang..."
install_asdf_language "erlang"

fancy_echo "Installing latest Elixir..."
install_asdf_language "elixir"
asdf reshim elixir

fancy_echo "Installing latest Node.js..."
install_asdf_language "nodejs"
